In [1]:
!pip install xlrd

Requirement already satisfied: xlrd in /opt/anaconda3/lib/python3.13/site-packages (2.0.2)

In [2]:
import pandas as pd
df = pd.read_excel("GSAF5.xls")

In [3]:
df

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,...,Great White Shark,US Sun: Mendocino Coast News:Melissa Michaelson:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,...,Unknown shark 5ft (1.5m),People Magazine: Kevin McMurray Trackingsharks...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,...,Great White Shark 10ft (3m),Perth Now: Kevin McMurray Trackingsharks.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,...,Unknown,News.com.au: ABC News: Andy Currie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,...,Tiger or bull shark implicated,Johannes Marchand: Andy Currie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN
7080,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN

In [4]:
#Reading and understanding data
df.columns

Index(['Date', 'Year', 'Type', 'Country', 'State', 'Location', 'Activity',
       'Name', 'Sex', 'Age', 'Injury', 'Fatal Y/N', 'Time', 'Species ',
       'Source', 'pdf', 'href formula', 'href', 'Case Number', 'Case Number.1',
       'original order', 'Unnamed: 21', 'Unnamed: 22'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7082 entries, 0 to 7081
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            7082 non-null   object
 1   Year            7080 non-null   float64
 2   Type            7064 non-null   object
 3   Country         7032 non-null   object
 4   State           6595 non-null   object
 5   Location        6515 non-null   object
 6   Activity        6499 non-null   object
 7   Name            6864 non-null   object
 8   Sex             6504 non-null   object
 9   Age             4088 non-null   object
 10  Injury          7047 non-null   object
 11  Fatal Y/N       6521 non-null   object
 12  Time            3555 non-null   object
 13  Species         3951 non-null   object
 14  Source          7062 non-null   object
 15  pdf             6799 non-null   object
 16  href formula    6794 non-null   object
 17  href            6796 non-null   object
 18  Case Number     6798 non-null   object
 19  Case Number.1   6797 non-null   object
 20  original order  6799 non-null   float64
 21  Unnamed: 21     1 non-null      object
 22  Unnamed: 22     2 non-null      object
dtypes: float64(2), object(21)
memory usage: 1.2+ MB

In [6]:
df.isnull().sum().sort_values(ascending =False) #21 & 22 have several 0 values

Unnamed: 21       7081
Unnamed: 22       7080
Time              3527
Species           3131
Age               2994
Activity           583
Sex                578
Location           567
Fatal Y/N          561
State              487
href formula       288
href               286
Case Number.1      285
Case Number        284
pdf                283
original order     283
Name               218
Country             50
Injury              35
Source              20
Type                18
Year                 2
Date                 0
dtype: int64

In [7]:
#Review Unnamed: 21 value: 
df["Unnamed: 21"].unique()

array([nan, 'stopped here'], dtype=object)

In [8]:
#Review Unnamed: 22 value: 
df["Unnamed: 22"].unique()

array([nan, 'Teramo', 'change filename'], dtype=object)

In [9]:
df["Sex"].unique()

array(['M', 'F', 'M ', '?', 'F ', nan, ' M', 'm', 'lli', 'M x 2', 'N',
       '.'], dtype=object)

In [11]:
df["Location"].unique()

array(['Big River Beach Mendocino County', 'Exmouth',
       'Lady Elliott Island', ..., 'Ocracoke Inlet',
       'Panama Bay 8ºN, 79ºW', 'Below the English fort, Trincomalee'],
      shape=(4627,), dtype=object)

In [12]:
df["Age"].unique()

array(['39', '?', "50's", '55', '13', '11', '27', '12', '26', '56', '24',
       '25', '61', '40', '14', '50+', '54', '48', '57', '8', '63', '9',
       '19', '7', '85', '69', '18', '66', '21', '37', '16', '20', '42',
       '45', '30', '30+', '40+', '29', 35, 58, 29, 24, 20, 55, 17, 12, 37,
       36, 23, 40, 28, 69, 48, '60+', 57, 45, 61, 27, 38, 16, 68, 33, 30,
       15, 41, 14, 43, 26, 'Middle age', 18, 21, 49, 25, 46, 19, 65, 64,
       nan, '46', '32', '10', '64', '62', '22', '15', '52', '44', '47',
       '59', '50', '34', '38', '30s', '20/30', '35', '65', '20s', '77',
       '60', '49', '!2', '73', '50s', '58', '67', '17', '6', '41', '53',
       '68', '43', '51', '31', 39, 51, 10, 13, 60, '40s', 62, 'teen', 8,
       22, 32, 56, 'Teen', 42, 50, 'M', 9, 31, 11, 34, '!6', '!!', 47, 7,
       71, 59, 53, 54, 75, '45 and 15', 73, 52, 70, 4, 63, 44, '28 & 22',
       '22, 57, 31', '60s', "20's", 67, 74, '9 & 60', 'a minor', 6, 3, 82,
       '40?', 66, 72, '23', '36', '71', '70', '18 months', '28', '33',
       '74', '3', '28 & 26', '5', '86', '18 or 20', '12 or 13', '46 & 34',
       '28, 23 & 30', 'Teens', 77, '36 & 26', '8 or 10', 84, '\xa0 ', ' ',
       '30 or 36', '6½', '21 & ?', '33 or 37', 'mid-30s', '23 & 20', 5,
       ' 30', '7      &    31', ' 28', '20?', "60's", '32 & 30',
       '16 to 18', '87', 'Elderly', 'mid-20s', 'Ca. 33', '74 ', '45 ',
       '21 or 26', '20 ', '>50', '18 to 22', 'adult', '9 & 12', '? & 19',
       '9 months', '25 to 35', '23 & 26', 1, '(adult)', '33 & 37',
       '25 or 28', '37, 67, 35, 27,  ? & 27', '21, 34,24 & 35', '30 & 32',
       '50 & 30', '17 & 35', 'X', '"middle-age"', '13 or 18', '34 & 19',
       '33 & 26', '2 to 3 months', '4', 'MAKE LINE GREEN', ' 43', '81',
       '"young"', '7 or 8', 78, '17 & 16', 'F', 'Both 11', '9 or 10',
       'young', '36 & 23', '  ', '78', 'A.M.', '?    &   14', '10 or 12',
       '31 or 33', '2½', '1', '13 or 14'], dtype=object)

In [13]:
#Duplicates

df[df.duplicated()]

Empty DataFrame
Columns: [Date, Year, Type, Country, State, Location, Activity, Name, Sex, Age, Injury, Fatal Y/N, Time, Species , Source, pdf, href formula, href, Case Number, Case Number.1, original order, Unnamed: 21, Unnamed: 22]
Index: []

[0 rows x 23 columns]

In [14]:
df.tail(10)

,Date,Year,Type,Country,State,Location,Activity,Name,Sex,Age,...,Species,Source,pdf,href formula,href,Case Number,Case Number.1,original order,Unnamed: 21,Unnamed: 22
7072,Circa 1862,0.0,Unprovoked,USA,Hawaii,Puna,NaN,"A ""chiefess""",F,NaN,...,NaN,Captain W. Young,ND-0010-Puna Hawaii.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0010,ND.0010,11.0,NaN,NaN
7073,Before 1906,0.0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,boy,M,NaN,...,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0009-boy-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0009,ND.0009,10.0,NaN,NaN
7074,Before 1906,0.0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,NaN,...,Blue pointer,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0008-Fisherman2-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0008,ND.0008,9.0,NaN,NaN
7075,Before 1906,0.0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,NaN,...,Blue pointers,"NY Sun, 9/9/1906, referring to account by Loui...",ND-0007 - Fisherman-Australia.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0007,ND.0007,8.0,NaN,NaN
7076,Before 1906,0.0,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,NaN,...,Said to involve a grey nurse shark that leapt ...,"L. Becke in New York Sun, 9/9/1906; L. Schultz...",ND-0006-ArabBoy-Prymount.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0006,ND.0006,7.0,NaN,NaN
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN
7080,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN

In [15]:
#Cleaning first steps
'''lowercase everything - Headers'''
df.columns =df.columns.str.lower()
df.tail(5)

,date,year,type,country,state,location,activity,name,sex,age,...,species,source,pdf,href formula,href,case number,case number.1,original order,unnamed: 21,unnamed: 22
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN
7080,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN

In [16]:
'''Drop completely empty lines '''

df = df.dropna(how ="all")
df.tail(5)

,date,year,type,country,state,location,activity,name,sex,age,...,species,source,pdf,href formula,href,case number,case number.1,original order,unnamed: 21,unnamed: 22
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,...,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,...,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,...,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN
7080,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,...,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,...,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN

In [17]:
'''Drop completly empty columns (Unnamed) '''

df = df.dropna(axis=1, how="all") #First double check if there's any othe with null and erase it

#Drop case number & case number.1
df= df.drop(columns=["unnamed: 21","unnamed: 22"])
df.tail(5)

,date,year,type,country,state,location,activity,name,sex,age,...,fatal y/n,time,species,source,pdf,href formula,href,case number,case number.1,original order
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,...,Y,NaN,NaN,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,...,Y,NaN,NaN,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0
7080,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,...,Y,NaN,NaN,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,...,Y,NaN,NaN,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0

In [18]:
#Last 7 columns cleaning
'''' Source, pdf, href formula & href cleaning (Not needed for analysis)'''

df = df.drop(columns=["source","pdf","href formula", "href"])
df.tail(5)

,date,year,type,country,state,location,activity,name,sex,age,injury,fatal y/n,time,species,case number,case number.1,original order
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,ND.0005,ND.0005,6.0
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,ND.0004,ND.0004,5.0
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,ND.0003,ND.0003,4.0
7080,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,ND.0002,ND.0002,3.0
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,ND.0001,ND.0001,2.0

In [19]:
'''Case Number (review if its duplicated with Case Number.1 and leave 1)'''
#Review if they are the same:
(df["case number"]== df["case number.1"]).all()

np.False_

In [20]:
(df["case number"]== df["case number.1"]).sum()

np.int64(6748)

In [21]:
df[df["case number"]!= df["case number.1"]] #Here it takes also NaN values as different!

,date,year,type,country,state,location,activity,name,sex,age,injury,fatal y/n,time,species,case number,case number.1,original order
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,NaN,NaN,NaN
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,Minor injuries,N,1015hrs,Unknown shark 5ft (1.5m),NaN,NaN,NaN
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,None reported damage to board,N,0800hrs,Great White Shark 10ft (3m),NaN,NaN,NaN
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,Lacerations elbow and abdomen,N,0815hrs,Unknown,NaN,NaN,NaN
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,Deep wounds arms and legs,Y,?,Tiger or bull shark implicated,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6955,Ca. 493 B.C.,0.0,Sea Disaster,GREECE,Off Thessaly,NaN,Shipwrecked Persian Fleet,males,M,NaN,Herodotus tells of sharks attacking men in the...,Y,NaN,NaN,493BC-PersianFleet,493BC,128.0
6956,Ca. 725 B.C.,0.0,Sea Disaster,ITALY,Tyrrhenian Sea,Krater found during excavations at Lacco Ameno...,Shipwreck,males,M,NaN,Depicts shipwrecked sailors attacked by a sha...,Y,NaN,NaN,725BC-vase,725/BC,127.0
6957,Ca. 1010 BC,0.0,NaN,JAPAN,NaN,Archeological site,NaN,male,M,NaN,FATAL,Y,NaN,NaN,1010BC-Japan,1010BC,126.0
6958,Ca 4000 BC,0.0,NaN,PERU,Paloma,Archeological site,NaN,male,M,17,FATAL,Y,NaN,NaN,4000.BC-Peru,4000BC,125.0
6959,Prior to 1988,0.0,Unprovoked,BELIZE,NaN,NaN,NaN,Charles Ritchie CBE,M,NaN,NaN,N,NaN,NaN,ND-0157,ND-157,124.0

In [22]:
#Review how many are different (Excluding NaNs)
df["case number"].equals(df["case number.1"])

False

In [23]:
'''Use case number.1 as base to only leave one (when we have NaN values on case number.1 use case number to fill)'''
#Generate a final column of case number and name it case_number_final

df["case_number_final"] = df["case number.1"].fillna(df["case number"])
df.tail(7)

,date,year,type,country,state,location,activity,name,sex,age,injury,fatal y/n,time,species,case number,case number.1,original order,case_number_final
7075,Before 1906,0.0,Unprovoked,AUSTRALIA,NaN,NaN,Fishing,fisherman,M,NaN,FATAL,Y,NaN,Blue pointers,ND.0007,ND.0007,8.0,ND.0007
7076,Before 1906,0.0,Unprovoked,AUSTRALIA,New South Wales,,Swimming,Arab boy,M,NaN,FATAL,Y,NaN,Said to involve a grey nurse shark that leapt ...,ND.0006,ND.0006,7.0,ND.0006
7077,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,NaN,FATAL,Y,NaN,NaN,ND.0005,ND.0005,6.0,ND.0005
7078,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,NaN,FATAL,Y,NaN,NaN,ND.0004,ND.0004,5.0,ND.0004
7079,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,NaN,FATAL,Y,NaN,NaN,ND.0003,ND.0003,4.0,ND.0003
7080,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ºN, 79ºW",NaN,Jules Patterson,M,NaN,FATAL,Y,NaN,NaN,ND.0002,ND.0002,3.0,ND.0002
7081,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,NaN,NaN,ND.0001,ND.0001,2.0,ND.0001

In [25]:
#Erase case number and case number.1 and only leave the merged column of case_number_final
df = df.drop(columns=["case number", "case number.1"])
df.head(7)

,date,year,type,country,state,location,activity,name,sex,age,injury,fatal y/n,time,species,original order,case_number_final
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,NaN,NaN
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,Minor injuries,N,1015hrs,Unknown shark 5ft (1.5m),NaN,NaN
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,None reported damage to board,N,0800hrs,Great White Shark 10ft (3m),NaN,NaN
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,Lacerations elbow and abdomen,N,0815hrs,Unknown,NaN,NaN
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,Deep wounds arms and legs,Y,?,Tiger or bull shark implicated,NaN,NaN
5,6th February,2026.0,Unprovoked,Cayman Islands,Little Cayman Island,Caribbean Sea,Diving,Bekley White,M,?,Minor puncture wounds to thigh,N,?,Juvenile Tiger shark 7ft (2.1m),NaN,NaN
6,29th January,2026.0,Unprovoked,Brazil,Recife,Del Chifre Beach in Olinda,Swimming,Deivson Rocha Dantas,M,13,Right thigh and lower leg stripped of flesh,Y,?,Unknown bull and tiger sharks frequent the area,NaN,NaN

In [28]:
#Renamed case_number_final to the case_number
df=df.rename(columns={"case_number_final":"case_number"})
df.head(5)

,date,year,type,country,state,location,activity,name,sex,age,injury,fatal y/n,time,species,original order,case_number
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,NaN,NaN
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,Minor injuries,N,1015hrs,Unknown shark 5ft (1.5m),NaN,NaN
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,None reported damage to board,N,0800hrs,Great White Shark 10ft (3m),NaN,NaN
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,Lacerations elbow and abdomen,N,0815hrs,Unknown,NaN,NaN
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,Deep wounds arms and legs,Y,?,Tiger or bull shark implicated,NaN,NaN

In [30]:
'''original order'''
#Removed the original order column - it does not provide analytical value + many null values
df = df.drop(columns=["original order"])
df.head(5)

,date,year,type,country,state,location,activity,name,sex,age,injury,fatal y/n,time,species,case_number
0,18th March,2026.0,Unprovoked,USA,California,Big River Beach Mendocino County,Surfing,Unknown,M,39,Injuries to both legs and feet,N,1715hrs,Great White Shark,NaN
1,14th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Swimming,Unknown,F,?,Minor injuries,N,1015hrs,Unknown shark 5ft (1.5m),NaN
2,10th March,2026.0,Unprovoked,Australia,Western Australia,Exmouth,Wing Foiling,Dave Daniell,M,?,None reported damage to board,N,0800hrs,Great White Shark 10ft (3m),NaN
3,5th March,2026.0,Unprovoked,Australia,Queensland,Lady Elliott Island,Snorkeling,Unknown,M,50's,Lacerations elbow and abdomen,N,0815hrs,Unknown,NaN
4,22nd February,2026.0,Unprovoked,New Caledonia,Noumea,Anse Vata near Point Magnin,Wing Foiling,Cyril Chevalier,M,55,Deep wounds arms and legs,Y,?,Tiger or bull shark implicated,NaN